version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    #   depends_on:
    #     - wordpress
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - ./requirements/nginx/tools/:/etc/nginx/ssl/
      - /home/${USER}/projects/inception/srcs/requirements/nginx/html:/var/www/
    restart: always

  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_ADMIN: ${DB_ADMIN}
        DB_ADMIN_PASS: ${DB_ADMIN_PASS}
        DB_USER: ${DB_USER}
        DB_USER_PASS: ${DB_USER_PASS}
        DB_ROOT: ${DB_ROOT}
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql
    restart: always

volumes:
  db-volume:
