version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    env_file: .env
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_USER_PASS: ${DB_USER_PASS}
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - ./requirements/nginx/tools/:/etc/nginx/ssl/
      - wp-volume:/var/www/
    restart: always

  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    #env_file: .env
      args:
        DB_NAME: ${DB_NAME}
        DB_ADMIN: ${DB_ADMIN}
        DB_ADMIN_PASS: ${DB_ADMIN_PASS}
        DB_USER: ${DB_USER}
        DB_USER_PASS: ${DB_USER_PASS}
        DB_ROOT: ${DB_ROOT}
    env_file: .env
    environment:
      DB_NAME: ${DB_NAME}
      DB_ADMIN: ${DB_ADMIN}
      DB_ADMIN_PASS: ${DB_ADMIN_PASS}
      DB_USER: ${DB_USER}
      DB_USER_PASS: ${DB_USER_PASS}
      DB_ROOT: ${DB_ROOT}
    container_name: mariadb
    ports:
      - "3306:3306"
    networks:
      - inception
    volumes:
      - db-volume:/var/lib/mysql
    restart: always
  
  wordpress:
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
    #env_file: .env
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_USER_PASS: ${DB_USER_PASS}
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/
    restart: always

volumes:
  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress

networks:
  inception:
    driver: bridge
